app: practice-app
on: push
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4
   - name: Install Node  
     uses: actions/setup-node@v4
      with:
       node-version: '20'       
     run: npm install
   - name: Test and lint
     run: |
       npm run lint
       npm run test
  deploy:
   runs-on: ubuntu-latest
   needs: test
   steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node  
      uses: actions/setup-node@v4
        with:
          node-version: '20'
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy
      run: echo "Deploying...."  


